sudo: required
services:
  - docker

before_install:
  - docker build  -t splitbrain1/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true splitbrain1/docker-react npm run test -- 

language: generic 
